### ISSUE TITLE
PHP implementation

### ISSUE THREAD

**Issue by rfantozzi** [google/gtfs-realtime-bindings#1]
Would like to see a PHP implementation. We use drupal @CDTA for out content management system.  We have pieced our own version together but would like to see something is a bit more standardized.

**Comment by bdferris** [comment]
I'm not much of a PHP programmer, so forgive me a few questions.  Are you using https://github.com/drslump/Protobuf-PHP as your protobuf implementation?  Do you have a preference on Composer vs Pear packages?

**Comment by poisa** [comment]
:+1: 
I would also love to see a PHP implementation. I do have a preference for Composer/Packagist since it is extremely easy to use and has overcome Pear in popularity nowadays.
Incidentally, I'm writing a PHP based CLI tool to convert GTFS files to sqlite/mysql/postgre databases. A PHP implementation of gtfs-realtime-bindings would be a very welcome addition to this suite of tools.

**Comment by bdferris** [comment]
Cool, I will try to make this happen.

**Comment by bdferris** [comment]
Ok, this was a little more complex than I hoped.  The PHP bindings themselves were straightforward, but to get the package published to Packagist, it was a real pain having the php files in a sub-directory of the GitHub project.  Ultimately, I had to create a new GitHub repo for the php files:

https://github.com/google/gtfs-realtime-bindings-php

The good news is that the package has now been published:

https://packagist.org/packages/google/gtfs-realtime-bindings

Try it out and let me know how it goes.

**Comment by poisa** [comment]
Holy commits Batman! That was quick! I'll give it a go during the week.
>it was a real pain having the php files in a sub-directory of the GitHub project

Indeed. I've used git submodules for this same purpose before.

**Comment by poisa** [comment]
Hey @bdferris I gave this a try and it works great. I only found one small bug but I'm *almost* sure it's in one of the underlying libraries (DrSlump\Protobuf\Message) not in your code. For example, the first thing I tried to quickly see what was coming in from the feed was to convert the feed to a plain php array. This only worked for the VehiclePositions feed but not for the Alerts or TripUpdates. The latter two were dumping some objects inside the array.

Here's a fully working example with different feeds to try.

```php
<?php
require_once 'vendor/autoload.php';
use transit_realtime\FeedMessage;

//$data = file_get_contents("http://developer.mbta.com/lib/GTRTFS/Alerts/Alerts.pb");
//$data = file_get_contents("http://developer.mbta.com/lib/GTRTFS/Alerts/TripUpdates.pb");
$data = file_get_contents("http://developer.mbta.com/lib/GTRTFS/Alerts/VehiclePositions.pb");

$feed = new FeedMessage();
$feed->parse($data);
print_r($feed->toArray());
```

By the way, this is just a minor issue since the DrSlump\Protobuf library comes with an extremely easy way to serialize feeds into many other formats:

```php
<?php

require_once 'vendor/autoload.php';

use transit_realtime\FeedMessage;
use \DrSlump\Protobuf\Codec;

//$data = file_get_contents("http://developer.mbta.com/lib/GTRTFS/Alerts/Alerts.pb");
//$data = file_get_contents("http://developer.mbta.com/lib/GTRTFS/Alerts/TripUpdates.pb");
$data = file_get_contents("http://developer.mbta.com/lib/GTRTFS/Alerts/VehiclePositions.pb");

$feed = new FeedMessage();
$feed->parse($data);

$codec = new Codec\PhpArray();
//$codec = new Codec\Json();
//$codec = new Codec\Xml();
//$codec = new Codec\TextFormat();

print_r($feed->serialize($codec));
```

One last thing, you might want to change the composer.json reccomendation on the README to point to "dev-master" instead of "x.y.z". This way people will always have the latest version and they can set it to a fixed version if the want to. Like so:

```json
{
  "require": {
    "google/gtfs-realtime-bindings": "dev-master"
  }
}
```

Having said that, a massive **thank you** for implementing this! It's extremely useful!

**Comment by bdferris** [comment]
Thanks for the comments @poisa.

Indeed, there appears to be a bug in the \DrSlump\Protobuf\Message toArray() method.  It seems it doesn't correctly handle the case where a value is an array of Messages (ironic in a way).  The following patch fixes the issue:

```
diff --git a/library/DrSlump/Protobuf/Message.php b/library/DrSlump/Protobuf/Message.php
index 2ea7694..c4f83cd 100644
--- a/library/DrSlump/Protobuf/Message.php
+++ b/library/DrSlump/Protobuf/Message.php
@@ -160,6 +160,12 @@ class Message implements MessageInterface
                 $result[$k] = $result[$k]->toArray();
             } else if ($result[$k] instanceof LazyRepeat) {
                 $result[$k] = $result[$k]->toArray();
+            } else if (is_array($result[$k])) {
+              foreach ($result[$k] as $k2=>$v2) {
+                if ($v2 instanceof MessageInterface) {
+                  $result[$k][$k2] = $v2->toArray();
+                }
+              }
             }
         }
         return $result;
```

The trick of course is getting it fixed in the actual library.  The original drslump/Protobuf-PHP has bugs and is no longer being maintained.  As such, I'm using centraldesktop/Protobuf-PHP instead... which also has bugs and is only sort of being maintained ;)  I'm currently using their 0.5.2 release because of bugs and api weirdness in the newer 0.6.x branch.  It might be possible to backport the fix and get a new release cut, but who knows?

Either way, thanks for the tip on the other export options.

As for "dev-master" for the version target, I'm a little reluctant to have people always link against head.  I'm worried I might put the repo in a broken state on accident, which a user might not easily realize.

**Comment by whitecat** [comment]
I am trying to use this package also. But I am facing problem with drslump/Protobuf-PHP.
After I do composer install, I try to run the phpunit test. But I always get the error 

`Fatal error:  Class 'DrSlump\Protobuf\Message' not found in /home/leetcat/web/c.albert-thompson.com/public_html/test/src/gtfs-realtime.php on line 24`

Do I need to install protobuf specifically?

**Comment by whitecat** [comment]
I fixed this error by adding `centraldesktop/Drslump` to the folder `/usr/share/php/`

<?php
require __DIR__ . '/../vendor/autoload.php';

require_once 'DrSlump/Protobuf.php';
\DrSlump\Protobuf::autoload();

use transit_realtime\FeedMessage;


class GtfsRealtimeTest extends PHPUnit_Framework_TestCase
{
  public function testParse()
  {
    $data = file_get_contents(dirname(__FILE__) . "/vehicle_position.pb");
    $feed = new FeedMessage();
    $feed->parse($data);
    $this->assertEquals(1, count($feed->getEntityList()));
    $entity = $feed->getEntity(0);
    $this->assertEquals("1", $entity->getId());
    $this->assertTrue($entity->hasVehicle());
  }
}

But I am still facing a problem with the example code. 

I get `PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Groups are deprecated in Protocol Buffers and unsupported by this library' in /usr/share/php/DrSlump/Protobuf/Codec/Binary/Native.php:225`

The transit  info I am trying to download is: `http://gtfs.translink.ca/gtfsrealtime?apikey=u8RWYB3HmxjsHenpDk0u`

What are groups? How do I still use them?
