### ISSUE TITLE
R bindings for realtime protobufs

### ISSUE THREAD

**Issue by hansthompson** [google/gtfs-realtime-bindings#19]
Hi.  I recently pushed out an R script to routinely produce the real-time protocol buffer for googlemaps.  I have signed the CLA and read CONTRIBUTING.md and I would like to push a fork of my contributions.  

What considerations should I take into account for my contribution?

**Comment by hansthompson** [comment]
I saw there was some activity for python and protobuf3 so I thought I would bump this issue.

**Comment by barbeau** [comment]
@hansthompson Is this still something you're interested in contributing?

**Comment by hansthompson** [comment]
yeah.

**Comment by barbeau** [comment]
@hansthompson For this bindings library we'll accept contributions if:
* The language is supported by the [official Google protobuf tooling](https://github.com/protocolbuffers/protobuf)
* The process of using the library in an application, as well as the process of generating the bindings when gtfs-realtime.proto changes, is well documented
* The process of renerating the bindings can be automated (we're working towards fully automating this process)

Unfortunately it looks like the official Google protobuf tools don't support R, so that eliminates R as a candidate until the official tools do support R.

However, if you want to host the R bindings in your own GitHub repo and maintain them we can point to 3rd party bindings repos from the README in this repo.

I'm going to close this issue for now, but feel free to re-open if you get the R bindings set up under your own repo, or if the Google protobuf tools start supporting R.
