### ISSUE TITLE
Version in PyPI is stale?

### ISSUE THREAD

**Issue by zanateh** [google/gtfs-realtime-bindings#21]
I was running into the same Python 3 problems as others. I see that it's been fixed and this package has been bumped to 0.0.5.

PyPI version is still 0.0.4 and contains the Python 3 bug.

**Comment by robbiet480** [comment]
See also #20.

@bdferris Can you publish the latest version to PyPI?

**Comment by robbiet480** [comment]
@egorich239 Pinging you again as well in the hopes of getting latest version put on PyPI...

**Comment by Holisticnature** [comment]
Hi Robbie, 

I see that PyPI is still on 0.04, and I do not see .05 on Python 3 Installer for conda. 

David

**Comment by robbiet480** [comment]
@Holisticnature I'm not a Google employee/owner of this library, so I have no control on releasing my fixes. I have tagged a bunch of people who work on this project in the hopes of having them update the version but have found no joy thus far.

**Comment by Holisticnature** [comment]
@robbiet480 Thanks providing me an update nonetheless. I am just trying to figure out the current status based on the forums. @egorich239 I am also interested in a Python 3 version for use on PyPI.

**Comment by axyjo** [comment]
This is my current solution for getting things to work in `requirements.txt`.


`-e git+https://github.com/axyjo/gtfs-realtime-bindings.git@afd68ef2093d14c1e7bdabb86ef2b88b5b800815#egg=gtfs_realtime_bindings`

**Comment by StevenMaude** [comment]
We'll be wishing the Python 3 fix a happy birthday soon :birthday:

It's almost a year old now, any chance of someone finally releasing it on PyPI, please? :slightly_smiling_face:

Just spent twenty minutes hitting the following error, diagnosing it, having to install the master branch by hand and finally documenting this process in the words you're reading now for the benefit of anyone else encountering the problem in future.

```
  File "check_gtfs_rt.py", line 1, in <module>
    from google.transit import gtfs_realtime_pb2
...
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: expected bytes, str found
```

**Comment by RachM** [comment]
I'm trying to get access to the account so that I can change it. Will post an update once that's done.

**Comment by ResidentMario** [comment]
@robbiet480 

When I install from source to get your `0.0.5` update:

```python
git clone https://github.com/google/gtfs-realtime-bindings.git
cd gtfs-realtime-bindings/python
python setup.py install
```

Then execute the code sample from the `README`, I get an import error:

`ModuleNotFoundError: No module named 'google.protobuf'`

When I try to do anything with `pip` afterwards, however (even running a bare `pip` command), I get this fascinating error:

    AttributeError: '_NamespacePath' object has no attribute 'sort'

This is a Python 3.5+ error that occurs due to implementation details with `pip` vendorizing `setuptools`. (cf. [setuptools#885](https://github.com/pypa/setuptools/issues/885) and [pip#4216](https://github.com/pypa/pip/issues/4216)). There's a namespace collision in `pip` internals that occurs when a package has a shared namespace (`gtfs-realtime-bindings` shares the `google` namespace with many of the bajillion other things Google releases AFAICT).

Reports of this error seems to be percolating through many of the rest of Google's packages as well, by the way, because many have this same issue.

Since this is unfortunately still an open issue in `pip` (since January! grumble grumble...), that seems to make installing this package exceedingly difficult in 3.5 or 3.6. I'm guessing you used 3.4 for development?

**Comment by ResidentMario** [comment]
Installing on `python-3.4` *does* work. So I guess for now the workaround is to stick to that version of Python.

**Comment by robbiet480** [comment]
@ResidentMario Thanks for the explanation of the issue. I don't think this is much we can do until Google as a whole decides on what to do. I don't really want to rename this package to something outside of the `google` namespace since it would break those that already implemented.

**Comment by ResidentMario** [comment]
Google mostly uses 2.7 internally, so they don't "eat their own dogfood", as the saying goes, when it comes to python-3 compat. I also think the Transit team builds the Protobuf tooling directly themselves, this package is an outwards-facing convenience. Hence the slowness of the response here.

I can't say for sure, of course, but my guess is that splitting up the namespace isn't going to happen. The problem has been fixed in `setuptools` trunk, but `pip` vendorizes `setuptools` for stability reasons, and the pin hasn't been updated yet, though people have been asking for it for a couple of months.

This isn't a blocker on this release, this release should go through as-is. But it's important to keep in mind that as things are, compatibility with 3.5+ isn't going to be a thing for a while.

**Comment by RachM** [comment]
Updated to 0.0.5.
